### ISSUE TITLE
SAVE DRAFT is inactive

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#100]
Once you create the file, and go back to edit; the option SAVE DRAFT is inactive, and we can only submit or cancel: 
![image](https://user-images.githubusercontent.com/40861938/43405613-3b47342e-93e8-11e8-8a43-d817db04a04b.png)

**Comment by WorkMAE** [comment]
This should now be fixed, see https://github.com/WorkMAE/CEM-Integration/issues/102

**Comment by Mberrady** [comment]
the issue is still pending

**Comment by Mberrady** [comment]
I just double checked the issue and when I update information I have the ability to submit or cancel but the option to save draft is not highlighted. please see below
![image](https://user-images.githubusercontent.com/40861938/43970636-323f0c64-9c9c-11e8-9751-3ab964e94119.png)

**Comment by WorkMAE** [comment]
This is the intended functionality.  Save Draft is ONLY meant to be used BEFORE it is submitted as a project. If you are editing the project record, there is no reason to save it as a draft, as the record has already been submitted and you would simply save the changes made to the project record to the Sharepoint List.

Now, if you saved a draft and then you loaded the draft and it wasn't able to be re-saved as a draft then this would be an issue since I made that correction and that should now be working properly, but I don't believe this is the case, that is working now.
