### ISSUE TITLE
Save draft Issue

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#102]
I used the ‘edit’ button to go back in and add the Implementation Contact.  It allowed me to enter the details, but there was no button to ‘submit’ once I completed the change.   Only option was ‘cancel’
![image](https://user-images.githubusercontent.com/40861938/43473194-7c7f857e-94bd-11e8-91e1-5bfa4b81cb10.png)
Without choosing ‘cancel’ I went ‘back home’ and viewed. The new contact I added was not present.

**Comment by WorkMAE** [comment]
Will need to figure out a way to determine if the project record is being loaded from a draft or from a project record that was already submitted.  Saving as a draft should not be available after the project has been submitted, only while it is in a draft state, but it should allow multiple saves to the draft before submitting instead of only one as it is now.

**Comment by WorkMAE** [comment]
This should now be fixed, all drafts that are reloaded are assigned an id of -1.  It then checks the id to determine whether to display the save draft button, as any project record must have an id greater than 0.  So this means it will only display the save draft button when it is being loaded from a draft or a new project record.

Also found an issue where it wasn't saving the CA outbound file format and services in the receivables form due to looking for a property in recServices and recOutboundFF instead of recCAServices and recCAOutboundFF
