### ISSUE TITLE
More Integrated Payables Observations

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#117]
I entered more data in the setups fields and they are not showing correctly in the view:  

![image](https://user-images.githubusercontent.com/40861938/43969982-ea1a21a0-9c99-11e8-85d7-6910ebca3d73.png)
When I go back into edit and double click the service there are no choices to select and the field stays populated with ACH.

**Comment by WorkMAE** [comment]
The view issue I will fix. Also, these are 2 separate issues and should be logged separately. Also FYI, this is Integrated Receivables.

In regards to edit mode, this is a known issue due to the way the grid handles a custom dropdown list.  I have created an issue on the ui-grid github site in regards to it and am waiting for them to fix it so I can test it out.

To make a change to a dropdown in the grid, you will need to double click and then erase the choice you made for the dropdown to reappear(if its one where you can enter your own). If it is a straight dropdown where there is no option to enter your own data, try re-selecting the country(ie, reclick on US) to see if it populates.  Let me know if that works.  I will take a look to see if there is a way I can make this work differently.

**Comment by WorkMAE** [comment]
View should be fixed now.
