### ISSUE TITLE
duplicate requests has not been fully resolved

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#121]
![image](https://user-images.githubusercontent.com/40861938/44033145-7259e548-9ed7-11e8-8365-3b4fac4ad142.png)

**Comment by WorkMAE** [comment]
I have added a check in the SaveDraft function that only will attempt to redirect if the function call is coming from pressing the Save Draft Button and not if its saving the project, since this already redirects to the main dashboard page.  

This should theoretically prevent the transition errors from occurring where it tries to re-load while another transition is already running and short circuits the process.  If this doesn't work I am not able to reproduce it because this hasn't happened for me in over a week now, where it was happening several times a day prior.
