### ISSUE TITLE
Email Alert Going to Wrong Person When ICE is Assigned

### ISSUE THREAD

**Issue by jacobdarling** [WorkMAE/CEM-Integration#18]
The following deal was assigned to Terry Miller.  It is reflected properly in the system, however this email alert was generated:

From: SharePoint Alerts 
Sent: Tuesday, December 19, 2017 4:23 PM
To: Foziah Alamari <foziah.alamari@us.hsbc.com>
Cc: Mahmoud Gaber <mahmoud.gaber@us.hsbc.com>; Metin A Erman <metin.a.erman@us.hsbc.com>
Subject: You have been assigned Mahle PRJ_0000751491 by 

Workflow Notification
________________________________________
Hello,

  has assigned the following project record to you:

 PRJ_0000751491

Click the link above to go directly to this Project Record or click the link below to go to your landing page on the ICE site:

 ICE Landing Page
 
________________________________________

**Comment by WorkMAE** [comment]
I am looking into the ICE assignment workflow and I am going to need to redo this from scratch with updated logic since it will send the email out every time its updated right now instead of only when the assignment has changed.   So we need to discuss logic of this and while I am in there I will try and decipher this mystery as well...

**Comment by FourUnbelievableCoolKids** [comment]
New version will have a full new workload.
