### ISSUE TITLE
Users are experiencing Error 403 When Submitting Form

### ISSUE THREAD

**Issue by jacobdarling** [WorkMAE/CEM-Integration#23]
Richard Bellamy received Error 403 upon submitting the engagement form.  Client name was Dixons.   This is the third time it happened.  All data disapears.

Can we have the form auto-save as data is input to avoid rework?

**Comment by WorkMAE** [comment]
This issue should be resolved.  The problem was occurring when the security certificate expired and was not renewed before saving the information.  I added code that basically pulls the "FormDigest" value before it saves so we always should have a valid value now.  In case of there being an issue I also added in functionality where it automatically saves it as a draft and notifies the user before redirecting back to the main page.
